# Generated by Django 3.2.7 on 2025-03-01 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.TextField()),
                ('question_type', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('user_answer', models.TextField()),
                ('test_title', models.CharField(max_length=255)),
                ('question_type', models.CharField(max_length=50)),
                ('marks_obtained', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
    ]
