# Generated by Django 3.2.7 on 2025-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamscore',
            name='tgpa_exam',
            field=models.FloatField(default=0.0),
        ),
    ]
