# Generated by Django 3.2.7 on 2025-03-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knotebook', '00011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('feedback', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knotebook.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='feedback_pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='feedtable',
        ),
    ]
