# Generated by Django 3.2.7 on 2025-02-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='tgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
