# Generated by Django 3.2.7 on 2025-02-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knotebook', '00011_initial'),
        ('essay', '0002_questionanswer_tgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knotebook.student_table'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('student', 'exam_title')},
        ),
    ]
