# Generated by Django 3.2.7 on 2025-02-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0004_auto_20250228_1636'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentresponse',
            unique_together=set(),
        ),
    ]
