# Generated by Django 3.2.7 on 2025-03-10 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0006_studentresponse_marks_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
